# Generated by Django 3.1.6 on 2021-09-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_auto_20210908_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='activate',
            new_name='active',
        ),
    ]
